version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apicoletalixoreciclavel-api
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - apicoletalixo-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

networks:
  apicoletalixo-network:
    driver: bridge
