services:
  apicoletalixoreciclavel:
    image: apicoletalixoreciclavel
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-coleta-lixo-reciclavel
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  app-logs:
    driver: local
