# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api:
    build:
      context: "/Users/vrsacardi/apicoletalixoreciclavel.net"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/apicoletalixoreciclavel.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "apicoletalixoreciclavel:dev"
    ports: []
    volumes:
    - "/Users/vrsacardi/apicoletalixoreciclavel.net:/app:rw"
    - "/Users/vrsacardi/apicoletalixoreciclavel.net:/src:rw"
    - "/Users/vrsacardi/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
